# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: thalamus-gpu-operator
spec:
  schema:
    apiVersion: v1alpha1
    kind: ThalamusGpuOperator
    scope: Namespaced
    spec:
      version: string | default="v26.3.3"
      prefix: string | default="thalamus-gpu-operator"
      myNamespace: string | default="gpu-operator"
      repository: object
      insecureRegistry: boolean | default=false
    status:
      ready: ${helmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
  resources:
    - id: myNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.myNamespace}

    - id: repository
      readyWhen:
        - ${repository.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Repository
        metadata:
          name: ${schema.spec.prefix}-repository
          namespace: ${myNamespace.metadata.name}
        spec:
          repositorySpec: ${schema.spec.repository}
          interval: 10m

    - id: component
      readyWhen:
        - ${component.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Component
        metadata:
          name: ${schema.spec.prefix}-component
          namespace: ${myNamespace.metadata.name}
        spec:
          component: github.com/cobaltcore-dev/thalamus/gpu-operator
          repositoryRef:
            name: ${repository.metadata.name}
          semver: ${schema.spec.version}
          interval: 1m

    - id: chartResource
      readyWhen:
        - ${chartResource.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-resource-chart
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: gpu-operator-chart
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: operatorImage
      readyWhen:
        - ${operatorImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-gpu-operator
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: gpu-operator-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: driverManagerImage
      readyWhen:
        - ${driverManagerImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-driver-manager
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: driver-manager-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: toolkitImage
      readyWhen:
        - ${toolkitImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-container-toolkit
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: container-toolkit-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: devicePluginImage
      readyWhen:
        - ${devicePluginImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-device-plugin
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: device-plugin-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: dcgmExporterImage
      readyWhen:
        - ${dcgmExporterImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-dcgm-exporter
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: dcgm-exporter-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: migManagerImage
      readyWhen:
        - ${migManagerImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-mig-manager
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: mig-manager-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: ccManagerImage
      readyWhen:
        - ${ccManagerImage.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: ${schema.spec.prefix}-image-cc-manager
          namespace: ${myNamespace.metadata.name}
        spec:
          componentRef:
            name: ${component.metadata.name}
          resource:
            byReference:
              resource:
                name: cc-manager-image
          additionalStatusFields:
            oci: resource.access.toOCI()

    - id: ociRepository
      readyWhen:
        - ${ociRepository.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: ${schema.spec.prefix}-oci-repository
          namespace: ${myNamespace.metadata.name}
        spec:
          interval: 1m0s
          insecure: ${schema.spec.insecureRegistry}
          layerSelector:
            mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
            operation: copy
          url: oci://${chartResource.status.additional.oci.registry}/${chartResource.status.additional.oci.repository}
          ref:
            digest: ${chartResource.status.additional.oci.digest}

    - id: helmRelease
      readyWhen:
        - ${helmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: gpu-operator
          namespace: ${myNamespace.metadata.name}
        spec:
          releaseName: gpu-operator
          targetNamespace: ${myNamespace.metadata.name}
          interval: 1m
          timeout: 5m
          chartRef:
            kind: OCIRepository
            name: ${ociRepository.metadata.name}
          values:
            nfd:
              enabled: false
            operator:
              repository: ${operatorImage.status.additional.oci.registry}
              image: ${operatorImage.status.additional.oci.repository}
              version: v26.3.3@${operatorImage.status.additional.oci.digest}
            validator:
              repository: ${operatorImage.status.additional.oci.registry}
              image: ${operatorImage.status.additional.oci.repository}
              version: ${operatorImage.status.additional.oci.digest}
            driver:
              manager:
                repository: ${driverManagerImage.status.additional.oci.registry}
                image: ${driverManagerImage.status.additional.oci.repository}
                version: v0.11.0@${driverManagerImage.status.additional.oci.digest}
            toolkit:
              repository: ${toolkitImage.status.additional.oci.registry}
              image: ${toolkitImage.status.additional.oci.repository}
              version: ${toolkitImage.status.additional.oci.digest}
            devicePlugin:
              repository: ${devicePluginImage.status.additional.oci.registry}
              image: ${devicePluginImage.status.additional.oci.repository}
              version: ${devicePluginImage.status.additional.oci.digest}
            gfd:
              repository: ${devicePluginImage.status.additional.oci.registry}
              image: ${devicePluginImage.status.additional.oci.repository}
              version: ${devicePluginImage.status.additional.oci.digest}
            dcgmExporter:
              repository: ${dcgmExporterImage.status.additional.oci.registry}
              image: ${dcgmExporterImage.status.additional.oci.repository}
              version: ${dcgmExporterImage.status.additional.oci.digest}
            migManager:
              repository: ${migManagerImage.status.additional.oci.registry}
              image: ${migManagerImage.status.additional.oci.repository}
              version: ${migManagerImage.status.additional.oci.digest}
            ccManager:
              repository: ${ccManagerImage.status.additional.oci.registry}
              image: ${ccManagerImage.status.additional.oci.repository}
              version: ${ccManagerImage.status.additional.oci.digest}
